-- SQL Dump for dbdiagram.io
-- Generated from MongoDB Schema Design

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar UNIQUE,
  "email" varchar UNIQUE,
  "passwordHash" varchar,
  "fullName" varchar,
  "phone" varchar,
  "role" varchar, -- enum: customer, staff, admin
  "avatarUrl" varchar,
  "loyaltyPoints" int DEFAULT 0,
  "membershipTier" varchar DEFAULT 'bronze',
  "staffDepartment" varchar, -- from staffProfile
  "staffStartDate" datetime,
  "createdAt" datetime DEFAULT (now()),
  "updatedAt" datetime DEFAULT (now())
);

CREATE TABLE "addresses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" int,
  "label" varchar DEFAULT 'Home',
  "recipientName" varchar,
  "phone" varchar,
  "street" varchar,
  "city" varchar,
  "district" varchar,
  "ward" varchar,
  "isDefault" boolean DEFAULT false
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "slug" varchar UNIQUE,
  "description" text,
  "parentId" int,
  "image" varchar,
  "isActive" boolean DEFAULT true
);

CREATE TABLE "products" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "slug" varchar UNIQUE,
  "sku" varchar UNIQUE,
  "categoryId" int,
  "price" decimal,
  "originalPrice" decimal,
  "description" text,
  "attributes" json, -- Store as JSON in SQL for visualization
  "images" json, -- Array of strings
  "stockQuantity" int DEFAULT 0,
  "isAvailable" boolean DEFAULT true,
  "metaTitle" varchar,
  "metaDescription" text,
  "averageRating" decimal DEFAULT 0,
  "reviewCount" int DEFAULT 0,
  "soldCount" int DEFAULT 0,
  "createdAt" datetime DEFAULT (now()),
  "updatedAt" datetime DEFAULT (now())
);

CREATE TABLE "inventory_logs" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "productId" int,
  "variantSku" varchar,
  "changeAmount" int,
  "reason" varchar, -- enum: import, sale, return, adjustment, damage
  "performedBy" int, -- userId (staff)
  "note" text,
  "createdAt" datetime DEFAULT (now())
);

CREATE TABLE "carts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" int UNIQUE,
  "updatedAt" datetime DEFAULT (now())
);

CREATE TABLE "cart_items" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cartId" int,
  "productId" int,
  "quantity" int DEFAULT 1,
  "selectedAttributes" json
);

CREATE TABLE "vouchers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar UNIQUE,
  "description" text,
  "discountType" varchar, -- percentage, fixed_amount
  "discountValue" decimal,
  "minOrderValue" decimal DEFAULT 0,
  "maxDiscountAmount" decimal,
  "startDate" datetime,
  "expirationDate" datetime,
  "usageLimit" int,
  "usedCount" int DEFAULT 0,
  "isActive" boolean DEFAULT true
);

CREATE TABLE "orders" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orderCode" varchar UNIQUE,
  "userId" int,
  "shippingRecipientName" varchar,
  "shippingPhone" varchar,
  "shippingAddress" text,
  "subtotal" decimal,
  "shippingFee" decimal DEFAULT 0,
  "discountAmount" decimal DEFAULT 0,
  "totalAmount" decimal,
  "paymentMethod" varchar, -- cod, banking, momo, vnpay
  "paymentStatus" varchar DEFAULT 'pending',
  "voucherId" int,
  "status" varchar DEFAULT 'pending',
  "createdAt" datetime DEFAULT (now()),
  "updatedAt" datetime DEFAULT (now())
);

CREATE TABLE "order_items" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orderId" int,
  "productId" int,
  "productName" varchar, -- Snapshot
  "productSku" varchar, -- Snapshot
  "productImage" varchar, -- Snapshot
  "quantity" int,
  "price" decimal, -- Unit price at purchase
  "total" decimal
);

CREATE TABLE "order_status_history" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orderId" int,
  "status" varchar,
  "changedBy" int, -- userId
  "note" text,
  "changedAt" datetime DEFAULT (now())
);

CREATE TABLE "reviews" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "productId" int,
  "userId" int,
  "orderId" int,
  "rating" int,
  "content" text,
  "images" json,
  "isPublished" boolean DEFAULT true,
  "replyContent" text,
  "repliedAt" datetime,
  "repliedBy" int, -- userId
  "createdAt" datetime DEFAULT (now()),
  UNIQUE ("orderId", "productId") -- Ensures user can only review a product once per order
);

CREATE TABLE "comments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "targetId" int, -- Polymorphic ID
  "targetModel" varchar, -- Product, Post, Lesson
  "userId" int,
  "content" text,
  "parentId" int,
  "isHidden" boolean DEFAULT false,
  "createdAt" datetime DEFAULT (now())
);

CREATE TABLE "chat_conversations" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" varchar DEFAULT 'support',
  "isActive" boolean DEFAULT true,
  "createdAt" datetime DEFAULT (now())
);

CREATE TABLE "chat_participants" (
  "conversationId" int,
  "userId" int,
  PRIMARY KEY ("conversationId", "userId")
);

CREATE TABLE "chat_messages" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "conversationId" int,
  "senderId" int,
  "content" text,
  "isRead" boolean DEFAULT false,
  "createdAt" datetime DEFAULT (now())
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar,
  "description" text,
  "thumbnail" varchar,
  "instructorId" int, -- userId
  "isActive" boolean DEFAULT true,
  "createdAt" datetime DEFAULT (now())
);

CREATE TABLE "modules" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "courseId" int,
  "title" varchar
);

CREATE TABLE "lessons" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "moduleId" int,
  "title" varchar,
  "content" text,
  "duration" int,
  "isRequired" boolean DEFAULT true
);

CREATE TABLE "employee_progress" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" int,
  "courseId" int,
  "status" varchar DEFAULT 'enrolled',
  "progressPercentage" decimal DEFAULT 0,
  "enrolledAt" datetime DEFAULT (now()),
  "completedAt" datetime
);

CREATE TABLE "employee_completed_lessons" (
  "progressId" int,
  "lessonId" int,
  PRIMARY KEY ("progressId", "lessonId")
);

-- Ref Definitions for dbdiagram.io
ALTER TABLE "addresses" ADD FOREIGN KEY ("userId") REFERENCES "users" ("id");

ALTER TABLE "categories" ADD FOREIGN KEY ("parentId") REFERENCES "categories" ("id");

ALTER TABLE "products" ADD FOREIGN KEY ("categoryId") REFERENCES "categories" ("id");

ALTER TABLE "inventory_logs" ADD FOREIGN KEY ("productId") REFERENCES "products" ("id");
ALTER TABLE "inventory_logs" ADD FOREIGN KEY ("performedBy") REFERENCES "users" ("id");

ALTER TABLE "carts" ADD FOREIGN KEY ("userId") REFERENCES "users" ("id");

ALTER TABLE "cart_items" ADD FOREIGN KEY ("cartId") REFERENCES "carts" ("id");
ALTER TABLE "cart_items" ADD FOREIGN KEY ("productId") REFERENCES "products" ("id");

ALTER TABLE "orders" ADD FOREIGN KEY ("userId") REFERENCES "users" ("id");
ALTER TABLE "orders" ADD FOREIGN KEY ("voucherId") REFERENCES "vouchers" ("id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("orderId") REFERENCES "orders" ("id");
ALTER TABLE "order_items" ADD FOREIGN KEY ("productId") REFERENCES "products" ("id");

ALTER TABLE "order_status_history" ADD FOREIGN KEY ("orderId") REFERENCES "orders" ("id");
ALTER TABLE "order_status_history" ADD FOREIGN KEY ("changedBy") REFERENCES "users" ("id");

ALTER TABLE "reviews" ADD FOREIGN KEY ("productId") REFERENCES "products" ("id");
ALTER TABLE "reviews" ADD FOREIGN KEY ("userId") REFERENCES "users" ("id");
ALTER TABLE "reviews" ADD FOREIGN KEY ("orderId") REFERENCES "orders" ("id");
ALTER TABLE "reviews" ADD FOREIGN KEY ("repliedBy") REFERENCES "users" ("id");

ALTER TABLE "comments" ADD FOREIGN KEY ("userId") REFERENCES "users" ("id");
ALTER TABLE "comments" ADD FOREIGN KEY ("parentId") REFERENCES "comments" ("id");

ALTER TABLE "chat_participants" ADD FOREIGN KEY ("conversationId") REFERENCES "chat_conversations" ("id");
ALTER TABLE "chat_participants" ADD FOREIGN KEY ("userId") REFERENCES "users" ("id");

ALTER TABLE "chat_messages" ADD FOREIGN KEY ("conversationId") REFERENCES "chat_conversations" ("id");
ALTER TABLE "chat_messages" ADD FOREIGN KEY ("senderId") REFERENCES "users" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("instructorId") REFERENCES "users" ("id");

ALTER TABLE "modules" ADD FOREIGN KEY ("courseId") REFERENCES "courses" ("id");

ALTER TABLE "lessons" ADD FOREIGN KEY ("moduleId") REFERENCES "modules" ("id");

ALTER TABLE "employee_progress" ADD FOREIGN KEY ("userId") REFERENCES "users" ("id");
ALTER TABLE "employee_progress" ADD FOREIGN KEY ("courseId") REFERENCES "courses" ("id");

ALTER TABLE "employee_completed_lessons" ADD FOREIGN KEY ("progressId") REFERENCES "employee_progress" ("id");
ALTER TABLE "employee_completed_lessons" ADD FOREIGN KEY ("lessonId") REFERENCES "lessons" ("id");
