const MESSAGE_MAP: Record<string, string> = {
  'Internal server error': 'Lỗi hệ thống',
  'Validation failed': 'Dữ liệu không hợp lệ',
  'Invalid token': 'Token không hợp lệ',
  Unauthorized: 'Chưa xác thực',
  Forbidden: 'Không có quyền',
  'Only image files are allowed': 'Chỉ cho phép file ảnh',
  'Invalid upload folder': 'Thư mục upload không hợp lệ',
  'Image file is required': 'Cần file ảnh',
  'Recipient email is required': 'Cần email người nhận',
  'subscription is required': 'Thiếu subscription',
  'endpoint is required': 'Thiếu endpoint',
  'At least one field is required': 'Cần ít nhất một trường',
  'brandId or brand is required': 'Cần brandId hoặc brand',
  'New password must be different from current password': 'Mật khẩu mới phải khác mật khẩu hiện tại',
  'expirationDate must be greater than startDate': 'Ngày hết hạn phải sau ngày bắt đầu',
  'discountValue for percentage must be <= 100': 'Giá trị giảm theo % phải <= 100',
  'discountValue for fixed amount must be smaller than minOrderValue':
    'Giá trị giảm tiền cố định phải nhỏ hơn đơn tối thiểu',
  'maxUsagePerUser must be smaller than usageLimit':
    'Giới hạn mỗi người dùng phải nhỏ hơn tổng lượt dùng',
  'Brand not found': 'Không tìm thấy thương hiệu',
  'Brand name is required': 'Cần tên thương hiệu',
  'Brand is inactive': 'Thương hiệu đang bị khóa',
  'Brand not found or inactive': 'Không tìm thấy thương hiệu hoặc đang bị khóa',
  'Brand is being used by products and cannot be deleted':
    'Thương hiệu đang được sử dụng và không thể xóa',
  'Cannot initialize cart': 'Không thể khởi tạo giỏ hàng',
  'Product not found': 'Không tìm thấy sản phẩm',
  'Variant not found': 'Không tìm thấy biến thể',
  'Variant does not belong to product': 'Biến thể không thuộc sản phẩm',
  'Variant does not belong to order': 'Sản phẩm không thuộc đơn hàng',
  'Variant is unavailable or out of stock': 'Biến thể không khả dụng hoặc đã hết hàng',
  'Address not found': 'Không tìm thấy địa chỉ',
  'Conversation not found': 'Không tìm thấy cuộc trò chuyện',
  'You are not a participant in this conversation': 'Bạn không thuộc cuộc trò chuyện này',
  'Message not found': 'Không tìm thấy tin nhắn',
  'Voucher not found': 'Không tìm thấy voucher',
  'Order is not eligible for review': 'Đơn hàng không đủ điều kiện đánh giá',
  'Review already exists for this order and product':
    'Đơn hàng này đã có đánh giá cho sản phẩm',
  'Review not found': 'Không tìm thấy đánh giá',
  'Order not found': 'Không tìm thấy đơn hàng',
  'Order not found by VNPay transaction': 'Không tìm thấy đơn hàng theo giao dịch VNPay',
  'Order payment method is not VNPay': 'Đơn hàng không dùng VNPay',
  'Order not found by ZaloPay transaction': 'Không tìm thấy đơn hàng theo giao dịch ZaloPay',
  'Order payment method is not ZaloPay': 'Đơn hàng không dùng ZaloPay',
  'Invalid VNPay signature': 'Chữ ký VNPay không hợp lệ',
  'Invalid ZaloPay checksum': 'Checksum ZaloPay không hợp lệ',
  'Order is not eligible for return': 'Đơn hàng chưa đủ điều kiện hoàn hàng',
  'Return request not found': 'Không tìm thấy yêu cầu hoàn hàng',
  'Cancel refund request not found': 'Không tìm thấy yêu cầu hoàn tiền đơn hủy',
  'Chatbot preset not found': 'Không tìm thấy câu hỏi chatbot',
  'At least one chatbot product is required': 'Cần chọn ít nhất một sản phẩm cho chatbot',
  'Some selected products do not exist': 'Có sản phẩm đã chọn không còn tồn tại',
  'Question is required': 'Cần nhập câu hỏi chatbot',
  'Cancel refund request already exists': 'Đơn hàng này đã có yêu cầu hoàn tiền',
  'Cancelled order is not eligible for refund request':
    'Chỉ đơn hàng đã hủy, đã thanh toán mới được yêu cầu hoàn tiền',
  'Refund request already completed': 'Yêu cầu hoàn tiền này đã được xử lý xong',
  'Bank account information is required': 'Cần nhập đầy đủ thông tin tài khoản ngân hàng',
  'Return items are required': 'Cần chọn sản phẩm để hoàn hàng',
  'Return quantity exceeds purchased quantity': 'Số lượng hoàn vượt quá số lượng đã mua',
  'Refund evidence images are required': 'Cần ảnh minh chứng hoàn tiền',
  'Order already paid': 'Đơn hàng đã được thanh toán',
  'Order is not paid by VNPay': 'Đơn hàng không dùng VNPay',
  'Cart is empty': 'Giỏ hàng trống',
  'No selected cart items to checkout': 'Không có sản phẩm được chọn để thanh toán',
  'Variant in cart not found': 'Không tìm thấy biến thể trong giỏ hàng',
  'Product in cart not found': 'Không tìm thấy sản phẩm trong giỏ hàng',
  'Course not found': 'Không tìm thấy khóa học',
  'Module not found': 'Không tìm thấy module',
  'Lesson not found': 'Không tìm thấy bài học',
  'You are not enrolled in this course': 'Bạn chưa ghi danh khóa học này',
  'Lesson does not belong to this course': 'Bài học không thuộc khóa học này',
  'Stock cannot be negative': 'Tồn kho không thể âm',
  'Could not generate SKU': 'Không thể tạo SKU',
  'Email already exists': 'Email đã tồn tại',
  'User not found': 'Không tìm thấy người dùng',
  'Admin role cannot be created via API': 'Không thể tạo tài khoản admin qua API',
  'Admin role cannot be assigned via API': 'Không thể gán quyền admin qua API',
  'Admin account cannot be deactivated': 'Không thể vô hiệu hóa tài khoản admin',
  'Account has been disabled': 'Tài khoản đã bị khóa',
  'Invalid email or password': 'Email hoặc mật khẩu không đúng',
  'Invalid refresh token': 'Refresh token không hợp lệ',
  'Refresh token does not belong to user': 'Refresh token không thuộc người dùng',
  'Current password is incorrect': 'Mật khẩu hiện tại không đúng',
  'Size not found': 'Không tìm thấy size',
  'Color not found': 'Không tìm thấy màu',
  'Category not found': 'Không tìm thấy danh mục',
  'Get users successfully': 'Lấy danh sách người dùng thành công',
  'Get user successfully': 'Lấy người dùng thành công',
  'Create user successfully': 'Tạo người dùng thành công',
  'Update user successfully': 'Cập nhật người dùng thành công',
  'Delete user successfully': 'Xóa người dùng thành công',
  'Get products successfully': 'Lấy danh sách sản phẩm thành công',
  'Get top selling products successfully': 'Lấy top sản phẩm bán chạy thành công',
  'Get newest products successfully': 'Lấy sản phẩm mới nhất thành công',
  'Get product filters successfully': 'Lấy bộ lọc sản phẩm thành công',
  'Get product successfully': 'Lấy sản phẩm thành công',
  'Create product successfully': 'Tạo sản phẩm thành công',
  'Update product successfully': 'Cập nhật sản phẩm thành công',
  'Delete product successfully': 'Xóa sản phẩm thành công',
  'Get product variants successfully': 'Lấy biến thể sản phẩm thành công',
  'Create product variant successfully': 'Tạo biến thể sản phẩm thành công',
  'Update product variant successfully': 'Cập nhật biến thể sản phẩm thành công',
  'Delete product variant successfully': 'Xóa biến thể sản phẩm thành công',
  'Get addresses successfully': 'Lấy địa chỉ thành công',
  'Create address successfully': 'Tạo địa chỉ thành công',
  'Update address successfully': 'Cập nhật địa chỉ thành công',
  'Delete address successfully': 'Xóa địa chỉ thành công',
  'Get comments successfully': 'Lấy bình luận thành công',
  'Get all comments successfully': 'Lấy tất cả bình luận thành công',
  'Create comment successfully': 'Tạo bình luận thành công',
  'Update comment visibility successfully': 'Cập nhật hiển thị bình luận thành công',
  'Delete comment successfully': 'Xóa bình luận thành công',
  'Get vouchers successfully': 'Lấy danh sách voucher thành công',
  'Get available vouchers successfully': 'Lấy voucher khả dụng thành công',
  'Get voucher successfully': 'Lấy voucher thành công',
  'Create voucher successfully': 'Tạo voucher thành công',
  'Update voucher successfully': 'Cập nhật voucher thành công',
  'Delete voucher successfully': 'Xóa voucher thành công',
  'Get categories successfully': 'Lấy danh sách danh mục thành công',
  'Get category successfully': 'Lấy danh mục thành công',
  'Create category successfully': 'Tạo danh mục thành công',
  'Update category successfully': 'Cập nhật danh mục thành công',
  'Delete category successfully': 'Xóa danh mục thành công',
  'Register successfully': 'Đăng ký thành công',
  'Login successfully': 'Đăng nhập thành công',
  'Reset password successfully': 'Đặt lại mật khẩu thành công',
  'Refresh token successfully': 'Làm mới token thành công',
  'Logout successfully': 'Đăng xuất thành công',
  'Get profile successfully': 'Lấy hồ sơ thành công',
  'Update profile successfully': 'Cập nhật hồ sơ thành công',
  'Change password successfully': 'Đổi mật khẩu thành công',
  'Service is healthy': 'Dịch vụ hoạt động bình thường',
  'Get reviews successfully': 'Lấy đánh giá thành công',
  'Get all reviews successfully': 'Lấy tất cả đánh giá thành công',
  'Create review successfully': 'Tạo đánh giá thành công',
  'Update review successfully': 'Cập nhật đánh giá thành công',
  'Delete review successfully': 'Xóa đánh giá thành công',
  'Moderate review successfully': 'Duyệt đánh giá thành công',
  'Reply review successfully': 'Phản hồi đánh giá thành công',
  'Get brands successfully': 'Lấy danh sách thương hiệu thành công',
  'Get brand successfully': 'Lấy thương hiệu thành công',
  'Create brand successfully': 'Tạo thương hiệu thành công',
  'Update brand successfully': 'Cập nhật thương hiệu thành công',
  'Delete brand successfully': 'Xóa thương hiệu thành công',
  'Test email sent successfully': 'Gửi email test thành công',
  'Subscribe push notification successfully': 'Đăng ký nhận thông báo thành công',
  'Unsubscribe push notification successfully': 'Hủy đăng ký thông báo thành công',
  'Get colors successfully': 'Lấy danh sách màu sắc thành công',
  'Get color successfully': 'Lấy màu sắc thành công',
  'Create color successfully': 'Tạo màu sắc thành công',
  'Update color successfully': 'Cập nhật màu sắc thành công',
  'Delete color successfully': 'Xóa màu sắc thành công',
  'Get cart successfully': 'Lấy giỏ hàng thành công',
  'Update cart successfully': 'Cập nhật giỏ hàng thành công',
  'Remove cart item successfully': 'Xóa sản phẩm khỏi giỏ hàng thành công',
  'Clear cart successfully': 'Xóa giỏ hàng thành công',
  'Create conversation successfully': 'Tạo cuộc trò chuyện thành công',
  'Get conversations successfully': 'Lấy danh sách cuộc trò chuyện thành công',
  'Join conversation successfully': 'Tham gia cuộc trò chuyện thành công',
  'Get messages successfully': 'Lấy tin nhắn thành công',
  'Send message successfully': 'Gửi tin nhắn thành công',
  'Mark message as read successfully': 'Đánh dấu đã đọc thành công',
  'Get sizes successfully': 'Lấy danh sách size thành công',
  'Get size successfully': 'Lấy size thành công',
  'Create size successfully': 'Tạo size thành công',
  'Update size successfully': 'Cập nhật size thành công',
  'Delete size successfully': 'Xóa size thành công',
  'Create order successfully': 'Tạo đơn hàng thành công',
  'Get orders successfully': 'Lấy đơn hàng thành công',
  'Get all orders successfully': 'Lấy tất cả đơn hàng thành công',
  'Get order successfully': 'Lấy đơn hàng thành công',
  'Cancel order successfully': 'Hủy đơn hàng thành công',
  'Create payment URL successfully': 'Tạo link thanh toán thành công',
  'Verify VNPay return successfully': 'Xác thực VNPay thành công',
  'Verify ZaloPay redirect successfully': 'Xác thực ZaloPay thành công',
  'Confirm order received successfully': 'Xác nhận đã nhận hàng thành công',
  'Create return request successfully': 'Tạo yêu cầu hoàn hàng thành công',
  'Create cancel refund request successfully': 'Tạo yêu cầu hoàn tiền thành công',
  'Update cancel refund request successfully': 'Cập nhật yêu cầu hoàn tiền thành công',
  'Update return request successfully': 'Cập nhật yêu cầu hoàn hàng thành công',
  'Update order status successfully': 'Cập nhật trạng thái đơn hàng thành công',
  'Get order statistics successfully': 'Lấy thống kê đơn hàng thành công',
  'Get chatbot response successfully': 'Lấy phản hồi chatbot thành công',
  'Get chatbot preset list successfully': 'Lấy danh sách câu hỏi chatbot thành công',
  'Get admin chatbot presets successfully': 'Lấy danh sách preset chatbot thành công',
  'Create chatbot preset successfully': 'Tạo preset chatbot thành công',
  'Update chatbot preset successfully': 'Cập nhật preset chatbot thành công',
  'Delete chatbot preset successfully': 'Xóa preset chatbot thành công',
  'Get inventory logs successfully': 'Lấy lịch sử tồn kho thành công',
  'Adjust stock successfully': 'Điều chỉnh tồn kho thành công',
  'Get courses successfully': 'Lấy danh sách khóa học thành công',
  'Get course detail successfully': 'Lấy chi tiết khóa học thành công',
  'Create course successfully': 'Tạo khóa học thành công',
  'Update course successfully': 'Cập nhật khóa học thành công',
  'Delete course successfully': 'Xóa khóa học thành công',
  'Create module successfully': 'Tạo module thành công',
  'Update module successfully': 'Cập nhật module thành công',
  'Delete module successfully': 'Xóa module thành công',
  'Create lesson successfully': 'Tạo bài học thành công',
  'Update lesson successfully': 'Cập nhật bài học thành công',
  'Delete lesson successfully': 'Xóa bài học thành công',
  'Enroll user successfully': 'Ghi danh người dùng thành công',
  'Get learning progress successfully': 'Lấy tiến độ học tập thành công',
  'Complete lesson successfully': 'Hoàn thành bài học thành công',
  'Upload image successfully': 'Tải ảnh lên thành công'
};

const translateByPattern = (message: string) => {
  const missingMatch = /^Missing (.+)$/i.exec(message);
  if (missingMatch) {
    return `Thiếu ${missingMatch[1]}`;
  }

  const invalidMatch = /^Invalid (.+)$/i.exec(message);
  if (invalidMatch) {
    return `${invalidMatch[1]} không hợp lệ`;
  }

  const routeMatch = /^Route not found: (.+)$/i.exec(message);
  if (routeMatch) {
    return `Không tìm thấy route: ${routeMatch[1]}`;
  }

  const variantOutOfStockMatch = /^Variant (.+) is out of stock$/i.exec(message);
  if (variantOutOfStockMatch) {
    return `Biến thể ${variantOutOfStockMatch[1]} đã hết hàng`;
  }

  return null;
};

export const localizeMessage = (message?: string) => {
  if (!message) {
    return message ?? '';
  }

  const normalized = message.trim();
  const mapped = MESSAGE_MAP[normalized];

  if (mapped) {
    return mapped;
  }

  const byPattern = translateByPattern(normalized);
  return byPattern ?? normalized;
};
